# 此文件仅供调试使用，实际部署时需要在云函数上配置环境变量
# Robot Info.
# 获取方式: https://open.feishu.cn/document/server-docs/api-call-guide/calling-process/get-access-token
ROBOT_INFO:
  APP_ID: cli_xxxxxxxxxxxx
  APP_SECRET: XXXXXXXXXXXXXXXXXXXXXX

# 获取方式：https://open.feishu.cn/document/server-docs/im-v1/message-card/overview
CARD_LIST:
  POETRY_CARD: ctp_xxxxxxxxxxxx
  MOVIE_CARD: ctp_xxxxxxxxxxxx

# 获取方式：https://lbs.amap.com/api/webservice/guide/api/weatherinfo
GAODE_INFO:
  GAODE_KEY: xxxxxxxxxxxxxxx